# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  voucherpool-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: ambientum/mysql:5.7
    container_name: voucherpool-mysql
    volumes:
      - voucherpool-mysql-data:/var/lib/mysql
      - ./database/:/docker-entrypoint-initdb.d
    ports:
      - "33306:3306"
    environment:
          - MYSQL_HOST=localhost
          - MYSQL_PORT=33306
          - MYSQL_ROOT_PASSWORD=voucher_pool
          - MYSQL_DATABASE=voucher_pool_db
          - MYSQL_USER=voucher_pool
          - MYSQL_PASSWORD=voucher_pool

  # PHP (with nginx)
  app:
    image: ambientum/php:7.1-nginx
    container_name: voucherpool-app
    volumes:
      - .:/var/www/app
    ports:
      - "8000:8000"
    links:
      - mysql
